// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7y8Yd9sQ1WSpXdD6K3Wf-mucj3dMZaTU',
    appId: '1:243278746903:web:3b31c7f5cfbb09e6d49352',
    messagingSenderId: '243278746903',
    projectId: 'journal-trend-anaylyzr-project',
    authDomain: 'journal-trend-anaylyzr-project.firebaseapp.com',
    storageBucket: 'journal-trend-anaylyzr-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTCcIDy3X92o_aLHqaPzLfBeBCWrjkDmY',
    appId: '1:243278746903:android:67b08c99c5603356d49352',
    messagingSenderId: '243278746903',
    projectId: 'journal-trend-anaylyzr-project',
    storageBucket: 'journal-trend-anaylyzr-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp7NrHG3J1GALcX6r4dIFClqI3Pm_kCb0',
    appId: '1:243278746903:ios:62bddf8495f409ded49352',
    messagingSenderId: '243278746903',
    projectId: 'journal-trend-anaylyzr-project',
    storageBucket: 'journal-trend-anaylyzr-project.firebasestorage.app',
    iosBundleId: 'com.example.project1Prm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBp7NrHG3J1GALcX6r4dIFClqI3Pm_kCb0',
    appId: '1:243278746903:ios:62bddf8495f409ded49352',
    messagingSenderId: '243278746903',
    projectId: 'journal-trend-anaylyzr-project',
    storageBucket: 'journal-trend-anaylyzr-project.firebasestorage.app',
    iosBundleId: 'com.example.project1Prm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7y8Yd9sQ1WSpXdD6K3Wf-mucj3dMZaTU',
    appId: '1:243278746903:web:fb44bb251c9334dfd49352',
    messagingSenderId: '243278746903',
    projectId: 'journal-trend-anaylyzr-project',
    authDomain: 'journal-trend-anaylyzr-project.firebaseapp.com',
    storageBucket: 'journal-trend-anaylyzr-project.firebasestorage.app',
  );
}
